name: Portfolio CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          cache-dependency-path: ./package-lock..json
      - name: Install dependencies
        run: npm ci
        working-directory: .
        
  eslint:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm i
    - name: Run Eslint
      run: npm run lint
